/**
 * Application error codes
 * Used for consistent error handling across backend and frontend
 */
export const ERROR_CODES = {
  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Validation
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
  CALENDAR_NOT_FOUND: 'CALENDAR_NOT_FOUND',
  CALENDAR_ENTRY_NOT_FOUND: 'CALENDAR_ENTRY_NOT_FOUND',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Business Logic
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  BUSINESS_ALREADY_EXISTS: 'BUSINESS_ALREADY_EXISTS',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_CODE: 'INVALID_CODE',
  CODE_EXPIRED: 'CODE_EXPIRED',
  SLOT_NOT_AVAILABLE: 'SLOT_NOT_AVAILABLE',
  BOOKING_CONFLICT: 'BOOKING_CONFLICT',

  // Database
  DATABASE_ERROR: 'DATABASE_ERROR',
  CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',

  // Server
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

// Extract type from the const object
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * Helper to check if a string is a valid error code
 */
export function isErrorCode(code: string): code is ErrorCode {
  return Object.values(ERROR_CODES).includes(code as ErrorCode);
}

/**
 * Error severity levels
 */
export const ERROR_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

export type ErrorSeverity =
  (typeof ERROR_SEVERITY)[keyof typeof ERROR_SEVERITY];

/**
 * HTTP status code mapping for error codes
 */
export const ERROR_STATUS_MAP = {
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.TOKEN_INVALID]: 401,
  [ERROR_CODES.SESSION_EXPIRED]: 401,

  [ERROR_CODES.BAD_REQUEST]: 400,
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.INVALID_INPUT]: 400,
  [ERROR_CODES.INVALID_CODE]: 400,
  [ERROR_CODES.CODE_EXPIRED]: 400,

  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.BUSINESS_NOT_FOUND]: 404,
  [ERROR_CODES.CALENDAR_NOT_FOUND]: 404,
  [ERROR_CODES.CALENDAR_ENTRY_NOT_FOUND]: 404,
  [ERROR_CODES.BOOKING_NOT_FOUND]: 404,
  [ERROR_CODES.USER_NOT_FOUND]: 404,

  [ERROR_CODES.DUPLICATE_ENTRY]: 409,
  [ERROR_CODES.BUSINESS_ALREADY_EXISTS]: 409,
  [ERROR_CODES.USER_ALREADY_EXISTS]: 409,
  [ERROR_CODES.BOOKING_CONFLICT]: 409,
  [ERROR_CODES.SLOT_NOT_AVAILABLE]: 409,

  [ERROR_CODES.CONSTRAINT_VIOLATION]: 400,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
} as const satisfies Record<ErrorCode, number>;
